name: Backend CI

on:
  push:
    branches: [ main, backend-dev, release ]
  pull_request:
    branches: [ main, backend-dev-#46, release ]
    
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Nuget Command
      run: nuget restore backend/CarbonFootprintVisualization.sln
    - name: Build
      run: dotnet build backend/CarbonFootprintVisualization.sln --no-restore
