# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [ backend-CI-Pipeline ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn add frontend/package.json frontend/package-lock.json --no-progress --non-interactive --no-lockfile 

      - name: Build
        run: yarn build 

      - name: Test
        run: yarn test --watchAll=false
